version: '3.3'
services:
  service-tests:
    build:
      context: ./src/service
      dockerfile: Dockerfile
    command: npm test
  ui-demo-tests:
    build:
      context: ./src/ui-demo
      dockerfile: Dockerfile
    command: npm test
